version: "3.8"
services:
  backend:
      build:
        context: server
        dockerfile: Dockerfile
      volumes:
        - ./server/src:/server/src
      ports:
        - "4000:4000"
      stdin_open: true
      restart: always
  